from . import student
from . import course
from . import teacher
from . import attendance
from . import academic
from . import admission
from . import assignment
from . import enrollment
from . import assignment
from . import submission